# Generated by Django 4.1 on 2022-08-29 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countIntStock',
            new_name='countInStock',
        ),
    ]
